### PR TITLE
Added support for HTTP keep-alive (switched to httplib2)

### PR DESCRIPTION
**Pull request by eriklax**
Connection: keep-alive will be available in SP 3.3-r2, which motivates this change

### CODE REVIEW

**Comment by uppfinnarn** [comment]
No need to pull in another library for this, I can just change it to use per-node requests sessions: http://docs.python-requests.org/en/latest/user/advanced/#keep-alive

I was going to before, then I realized that it wouldn't be any faster anyways because the server actively forces `Connection: close`...

**Comment by eriklax** [comment]
That would be nicer! I think the modules/cmd.py change should go in, it prevents a second delay on typing,  but it should be tested together with keep-alive.

**Comment by uppfinnarn** [comment]
That whole loop could be removed, really, since the only time when it'd fire twice would be if you somehow fed it more at once than can be read in a single read() call... which is an insane amount of data :/

I'm not sure why I put it in, habits from C select, maybe?

**Comment by eriklax** [comment]
I was about to change it to an "if"-statement, but some key strokes (eg. arrow up \x1b[A) trigger more than one byte which the loop optimizes.

**Comment by uppfinnarn** [comment]
`f.read()` will actually read all data that's currently available, or until an EOF is encountered: https://docs.python.org/2/tutorial/inputoutput.html#methods-of-file-objects

The `select()` call is there because if there is nothing available, `read()` will block indefinitely until it gets at least one byte to read.

**Comment by eriklax** [comment]
We really need keep-alive when doing interactive (-i). Is it an easy fix to add or should we commit this pull-request in the meantime?

**Comment by uppfinnarn** [comment]
Oh, it's a pretty easy fix, I'll get to it

**Pull request closed without merging**
